/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente.interfaces;

import Cliente.cliente.ListaCustomizada;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ListSelectionModel;
import cliente.cliente.Chat;

/**
 *
 * @author gerar
 */
public class ListaUsuariosActivosChats extends javax.swing.JPanel {
    private String nombreUsuarioLocal;
    private ListaCustomizada modeloListaUsuariosActivos;
    private ListaCustomizada modeloListaChatsPrivados;
    private List<Chat> listaSalas;

    /**
     * Creates new form listaUsuariosActivos
     */
    public ListaUsuariosActivosChats(String nombreUsuario) {
        this.nombreUsuarioLocal = nombreUsuario;
        modeloListaUsuariosActivos = new ListaCustomizada();
        modeloListaChatsPrivados = new ListaCustomizada();
        listaSalas = new ArrayList<>();
        initComponents();
    }

    public void setNuevoUsuarioConectado(String nombre) {
        modeloListaUsuariosActivos.addUsuario(nombre);
    }

    public void quitarUsuarioConectado(String nombre) {
        int selection = listListaUsuarios.getSelectedIndex();
        if (selection != -1) {
            modeloListaUsuariosActivos.eliminarUsuario(selection);
        }
    }
    public void cargarChatPrincipal(){
        Chat chat = new Chat();        
    }
    
    public void agregarChatPrivado(int index){
        Chat chat = new Chat(this.nombreUsuarioLocal,modeloListaUsuariosActivos.getUsuario(index));
        listaSalas.add(chat.crearNuevaSala());
        modeloListaChatsPrivados.addUsuario(chat.getNombreChat());   
    }
    public void quitarChatPrivado(int index){
        int selection = listListaSalas.getSelectedIndex();
        if (selection != -1) 
            modeloListaChatsPrivados.eliminarUsuario(selection); 
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabUsuariosSalas = new javax.swing.JTabbedPane();
        panelUsuariosActivos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listListaUsuarios = new javax.swing.JList<>();
        listListaUsuarios.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        botonCrearPrivado = new javax.swing.JButton();
        panelSalasPrivadas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listListaSalas = new javax.swing.JList<>();
        botonCerrarChat = new javax.swing.JButton();

        tabUsuariosSalas.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N

        listListaUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        listListaUsuarios.setModel(modeloListaUsuariosActivos);
        jScrollPane1.setViewportView(listListaUsuarios);

        botonCrearPrivado.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        botonCrearPrivado.setText("Enviar privado");

        javax.swing.GroupLayout panelUsuariosActivosLayout = new javax.swing.GroupLayout(panelUsuariosActivos);
        panelUsuariosActivos.setLayout(panelUsuariosActivosLayout);
        panelUsuariosActivosLayout.setHorizontalGroup(
            panelUsuariosActivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsuariosActivosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonCrearPrivado)
                .addGap(69, 69, 69))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsuariosActivosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        panelUsuariosActivosLayout.setVerticalGroup(
            panelUsuariosActivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsuariosActivosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCrearPrivado, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabUsuariosSalas.addTab("Usuarios activos", panelUsuariosActivos);

        listListaSalas.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        listListaSalas.setModel(modeloListaChatsPrivados);
        jScrollPane2.setViewportView(listListaSalas);

        botonCerrarChat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botonCerrarChat.setText("Cerrar chat privado");

        javax.swing.GroupLayout panelSalasPrivadasLayout = new javax.swing.GroupLayout(panelSalasPrivadas);
        panelSalasPrivadas.setLayout(panelSalasPrivadasLayout);
        panelSalasPrivadasLayout.setHorizontalGroup(
            panelSalasPrivadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSalasPrivadasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSalasPrivadasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonCerrarChat)
                .addGap(61, 61, 61))
        );
        panelSalasPrivadasLayout.setVerticalGroup(
            panelSalasPrivadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSalasPrivadasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCerrarChat, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        tabUsuariosSalas.addTab("Salas", panelSalasPrivadas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabUsuariosSalas)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabUsuariosSalas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCerrarChat;
    private javax.swing.JButton botonCrearPrivado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listListaSalas;
    private javax.swing.JList<String> listListaUsuarios;
    private javax.swing.JPanel panelSalasPrivadas;
    private javax.swing.JPanel panelUsuariosActivos;
    private javax.swing.JTabbedPane tabUsuariosSalas;
    // End of variables declaration//GEN-END:variables
}
