/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente.interfaces;

import Cliente.interfaces.VistaChat;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.Arrays;
import javax.swing.JOptionPane;
import cliente.cliente.Cliente;

/**
 *
 * @author gerar
 */
public class LogeoCliente extends javax.swing.JFrame {

    /**
     * Creates new form logeoCliente
     */
    public LogeoCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNombreUsuario = new javax.swing.JLabel();
        labelContraseñaUsuario = new javax.swing.JLabel();
        textFieldNombreUsuario = new javax.swing.JTextField();
        butonEnviar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        contraseniaUsuario = new javax.swing.JPasswordField();
        registrarUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelNombreUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNombreUsuario.setText("Nombre de usuario");

        labelContraseñaUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelContraseñaUsuario.setText("Contraseña de usuario");

        textFieldNombreUsuario.setText("Nombre de usuario");

        butonEnviar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        butonEnviar.setLabel("Enviar");
        butonEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butonEnviarMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Raleway", 0, 24)); // NOI18N
        jLabel1.setText("Verifica si existes en nuestra BD");

        contraseniaUsuario.setText("myDog");

        registrarUsuario.setText("Registrar con los mismos datos");
        registrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelContraseñaUsuario)
                            .addComponent(labelNombreUsuario))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFieldNombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(contraseniaUsuario))
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(registrarUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butonEnviar)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombreUsuario)
                    .addComponent(textFieldNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelContraseñaUsuario)
                    .addComponent(contraseniaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butonEnviar)
                    .addComponent(registrarUsuario))
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarUsuarioActionPerformed
        String contrasenia = Arrays.toString(contraseniaUsuario.getPassword());
        Cliente cliente = new Cliente(textFieldNombreUsuario.getText(),contrasenia);
        try{
            boolean usuarioRegistrado = cliente.registrarUsuario();
            if (!usuarioRegistrado){
                JOptionPane.showMessageDialog(null, "No se pudo registrar ", "Error", JOptionPane.WARNING_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null, "El usuario pudo registrarse", "Registro exitoso", JOptionPane.INFORMATION_MESSAGE);                
            }
        }catch (RemoteException e){
            System.out.println(e.getMessage());
        }catch (NotBoundException e){
            System.out.println("Not Bound");
        }
    }//GEN-LAST:event_registrarUsuarioActionPerformed

    private void butonEnviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butonEnviarMouseClicked
        String contrasenia = Arrays.toString(contraseniaUsuario.getPassword());
        Cliente cliente = new Cliente(textFieldNombreUsuario.getText(),contrasenia);
        try{
            boolean usuarioValido = cliente.validarUsuario();
            if (!usuarioValido){
                JOptionPane.showMessageDialog(null, "Considere crear un usuario ", "Usuario inexistente", JOptionPane.WARNING_MESSAGE);
            }else{
                VistaChat chat = new VistaChat();
                chat.pasarNombre(textFieldNombreUsuario.getText());
                chat.setVisible(true);
            }
        }catch (RemoteException e){
            System.out.println(e.getMessage());
        }catch (NotBoundException e){
            System.out.println("Not Bound");
        }
    }//GEN-LAST:event_butonEnviarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogeoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogeoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogeoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogeoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogeoCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butonEnviar;
    private javax.swing.JPasswordField contraseniaUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelContraseñaUsuario;
    private javax.swing.JLabel labelNombreUsuario;
    private javax.swing.JButton registrarUsuario;
    private javax.swing.JTextField textFieldNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
